config/routes.rb
Rewsly::Application.routes.draw do
  devise_for :users

  root 'stories#index'
  resources :stories do
    resources :comments, only: :create
  end
  get 'search', to: 'stories#search'
  
  post 'reddit/save/', to: 'stories#create', as: :reddits_save
  get 'subreddit/new/', to: 'subreddits#new', as: :subred_list
  get 'subreddit/new/:id/stories', to: 'subreddits#reddit_stories', as: :reddits

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
end

app/models/story.rb
class Story < ActiveRecord::Base
  
  require 'rest_client'
  require 'json'

  validates :title, :link, :category, :upvotes, presence: true
  validates :title, :link, uniqueness: true

  scope :popular, -> { where('upvotes >= ?', 4)}
  scope :recent, -> { where('created_at >= ?', Date.today)}

  belongs_to :user
  has_many :comments
  has_many :commenters, through: :comments, source: :user

  def self.search_for(query)
    where('title LIKE :query OR category LIKE :query', query: "%#{query}%")
  end

  def self.get_remote_stories(subreddit="r/worldnews")
    parsed_response = JSON.load(RestClient.get("http://reddit.com/#{subreddit}.json"))
    parsed_response["data"]["children"].collect do |reddit|
      { title: reddit["data"]["title"], category: reddit["data"]["subreddit"], link: reddit["data"]["url"], upvotes: reddit["data"]["ups"] }
    end
  end


end

app/models/subreddit.rb
  class Subreddit < ActiveRecord::Base

  require 'rest_client'
  require 'json'

  validates :subreddit, :name, :image, presence: true, uniqueness: true

  belongs_to :user

  def self.get_subreddits
    parsed_response = JSON.load(RestClient.get("http://reddit.com/reddits.json"))
    parsed_response["data"]["children"].each_with_index.collect do |subreddit,i|
      { subreddit: subreddit["data"]["url"], image: subreddit["data"]["header_img"], name: subreddit["data"]["display_name"] }
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :comments
  has_many :subreddits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if user_signed_in?
      safe_comment = params.require(:comment).permit(:post).merge(story_id: params[:story_id])
      @comment = current_user.comments.create safe_comment
      redirect_to @comment.story
    else
      redirect_to new_user_session_path, alert: "Only logged in users can create comments"
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :index]
  
  def index
    @stories = Story.where(user_id: current_user.id)
    #@stories = Story.all
  end

  def show
    @story = Story.find params[:id]
    @comment = @story.comments.new
  end
  

  def new
    @story = Story.new
  end

  def create
    @story = current_user.stories.build(story_params)
    @story.upvotes = 1
    if @story.save
      redirect_to @story
    else
      render :new
    end
  end

  def search
    @stories = Story.search_for params[:q]
  end

  def destroy
    @story = Story.find(params[:id])
    if @story.present?
      @story.destroy
      flash[:notice] = "The story with link '#{@story.link}' has been removed"
    end
    redirect_to :action => 'index'
  end


private

  def story_params
    params.require(:story).permit(:title, :link, :category)
  end

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController  
  before_action :authenticate_user!, only: [:new, :reddit_stories]

  def new
    @subreddits = Subreddit.get_subreddits.collect do |subreddit|
      @subreddit = Subreddit.new({name: subreddit[:name], image: subreddit[:image], subreddit: subreddit[:subreddit]})
      if @subreddit.save
        @subreddit
      else
        @subreddit.destroy
      end 
    end
  end

  def reddit_stories
    @stories = Story.get_remote_stories(Subreddit.find(params[:id])[:subreddit]).collect do |reddit|
      @story = Story.new({title: reddit[:title], link: reddit[:link], upvotes: reddit[:upvotes], category: reddit[:category], user_id: current_user.id})
      if @story.save
        @story
      else
        @story.destroy
      end
    end
    redirect_to stories_path
    #rescue statement to ensure the loop always finishes
    #if it breaks display the error
    #but move this all to the model
    
  end
  
# private

#   def subreddit_params
#     params.require(:subreddit).permit(:name, :image, :subreddit)
#   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <link rel="shortcut icon" href="/favicon.png" type="image/ico" />
    <meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Rewsly" %></title>

  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "All Stories", stories_path %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "Browse Stories", stories_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Add a Story", new_story_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Our Partners" %></li>
          <li class="divider"></li>
          <li><%= link_to "Contact Us" %></li>
        </ul>
      </div>
    </nav>

  
  <div class="row">

    <div class="small-8 columns">
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
   
    </div>  
      
    <div class="small-4 columns">
      <h2 class="subheader">About Us</h2>
      <p line-height="1.0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id iaculis tellus. Pellentesque vel rutrum turpis. Sed in mauris feugiat elit sollicitudin pellentesque eu vel magna. Sed ac arcu nisl. Nunc vulputate non velit porttitor posuere. Suspendisse imperdiet luctus iaculis. Praesent vitae dictum purus. Suspendisse tristique justo vitae cursus dapibus. Ut varius sodales dolor, eu hendrerit orci hendrerit sit amet. In cursus sem et dictum mattis. Quisque posuere mauris nec elit elementum, et volutpat massa tincidunt. Cras id eleifend lacus. Vivamus facilisis condimentum neque, ut posuere augue sollicitudin semper. Vivamus rutrum accumsan nisl et porta. Mauris porta, urna et hendrerit hendrerit, felis turpis lacinia velit, et malesuada tortor elit eget tortor. Sed mattis mollis turpis at laoreet.</p>

      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "small button alert" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "tiny button success" %> | <%= link_to "Sign in", new_user_session_path, class: "tiny button" %>
      <% end %>

    </div>
  </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/stories/_form.html.erb
<% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<%= form_for @story do |f| %>
  <fieldset>
    
    <div class="row collapse">
      <div class="small-3 columns"><%= f.label :title, class: "right inline" %></div>
      <div class="small-9 columns"><%= f.text_field :title, placeholder: "insert title" %></div>
    </div>

    <div class="row collapse">
      <div class="small-3 columns"><%= f.label :link, class: "right inline" %></div>
      <div class="small-9 columns"><%= f.text_field :link, placeholder: "insert url" %></div>
    </div>

    <div class="row collapse">
      <div class="small-3 columns"><%= f.label :category, class: "right inline" %></div>
      <div class="small-9 columns"><%= f.text_field :category, placeholder: "insert category" %></div>
    </div>

    <div class="row collapse">
      <div class="small-9 small-offset-3 columns"><%= f.submit "Go!" %></div>
    </div>

  </fieldset>
 
<% end %>

app/views/stories/_search.html.erb
<%= form_tag search_path, method: :get do %>

<div class="row">
	<div class="small-8 columns left inline">

	<%= search_field_tag :q, params[:q] %>
	<%= submit_tag "Find a story", class: "tiny button round" %>
	<% end %>
	
	</div>
</div>

app/views/stories/_story.html.erb
<article>
  <li>
  <header>
    <%= link_to story.title, story.link, class: "tiny button round secondary" %>
  </header>
  <p>Upvotes: <%= story.upvotes %> | 
  Category: <%= story.category %> |
  <%= link_to "Comments", story %> | <%= link_to "Remove", story, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </li>
</article>

app/views/stories/index.html.erb
<%= link_to "Add a new story", new_story_path, class: "button radius neutral" %>

<h1>Welcome to Rewsly, your news aggregator</h1>

<%= render 'search'%>

<section id="stories">
  <ul>
    <%= render @stories.sort_by(&:upvotes).reverse %>
  </ul>
</section>

app/views/stories/new.html.erb
<h1 class="header">Add your own story!</h1>

<%= render 'form' %>

<h3 class="subheader">
	Or <%=link_to "add stories using Reddit", subred_list_path %>...
</h3>

app/views/stories/search.html.erb
<h1>Results</h1>
<%= render 'search' %>
<section id="stories">
  <ul>
    <%= render @stories %>
  </ul>
</section>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<p><%= link_to @story.link, @story.link %>
<p><%= link_to "Back to home page", root_path %></p>

<%= form_for [@story, @comment] do |f| %>
  <p>
    <%= f.text_area :post, placeholder: "Add a comment..." %>
  </p>
  <%= f.submit %>
<% end %>

<ul class="comments">
  <% @story.comments.each do |comment| %>
    <li><%= "#{comment.user.try(:email)} posted: #{comment.post}" %></li>
  <% end %>
</ul>

app/views/subreddits/new.html.erb
<h1 class="subheader">Choose your subreddit, the category of news you want...</h1>

<table>
	<tr>
		<th>subreddit</th>
		<th>.png</th>
		<th>pick one</th>
	</tr>

  <% Subreddit.all.each do |r| %>
	<tr>
		<td><%= r[:name] %></td>
		<td><a href=<%= "http://www.reddit.com#{r[:subreddit]}" %>><img src=<%= r[:image] %>></a></td>
		<td><%= link_to r[:name], reddits_path(r[:id]) %></td>
	</tr>
  <% end %>
</table>

app/views/subreddits/reddit_stories.html.erb
<h2 class="subheader"><%=link_to "Save these stories to my Rewsly feed!", reddits_save_path, method: :post %></h2>

<% if @reddits.empty? %>
<p>There aren't any stories in that subreddit :(</p>
<% end %>

<% @reddits.each do |reddit| %>

	<h1><%= reddit.title %></h1>
	<p><%= link_to reddit.link, reddit.link %>
	<p><%= link_to "Back to home page", root_path %></p>

<% end %>


<ul class="comments">
  <% @reddit.comments.each do |comment| %>
    <li><%= "#{comment.user.try(:email)} posted: #{comment.post}" %></li>
  <% end %>
</ul>


<p></p>
<p>
	<%= link_to "Home ", root_path %>
	<%= link_to " |  Add Custom Story", new_story_path %>
</p>